# Generated by Django 4.1.3 on 2022-12-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asukkaat',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'asukkaat',
            },
        ),
        migrations.CreateModel(
            name='Palvelut',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('plv_nimi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'palvelut',
            },
        ),
        migrations.CreateModel(
            name='Sopimus',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('osoite_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sopimus',
            },
        ),
        migrations.CreateModel(
            name='Tilaaja',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tilaaja',
            },
        ),
        migrations.CreateModel(
            name='Tyontekijat',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tyontekijat',
            },
        ),
        migrations.CreateModel(
            name='Osoite',
            fields=[
                ('id', models.OneToOneField(db_column='Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hoivakoti_browser.sopimus')),
                ('osoite', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'osoite',
            },
        ),
        migrations.AddField(
            model_name='sopimus',
            name='plv_vastaava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hoivakoti_browser.tyontekijat'),
        ),
        migrations.AddField(
            model_name='sopimus',
            name='tilaaja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hoivakoti_browser.tilaaja'),
        ),
        migrations.CreateModel(
            name='Palvelukori',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('asukas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hoivakoti_browser.asukkaat')),
                ('plv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hoivakoti_browser.palvelut')),
            ],
            options={
                'db_table': 'palvelukori',
            },
        ),
        migrations.AddField(
            model_name='asukkaat',
            name='osoite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hoivakoti_browser.osoite'),
        ),
    ]
