# Generated by Django 4.1.3 on 2022-11-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asujat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asujat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asukkaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'asukkaat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Palvelut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plv_nimi', models.CharField(blank=True, max_length=50, null=True)),
                ('kuvaus', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'palvelut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sopimus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osoite', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sopimus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tilaajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tilaajat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tyontekijat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(blank=True, max_length=50, null=True)),
                ('esimies', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tyontekijat',
                'managed': False,
            },
        ),
    ]
