# Generated by Django 4.1.3 on 2022-12-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoivakoti_browser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoite',
            old_name='id',
            new_name='sopimus',
        ),
    ]
