# Generated by Django 4.1.3 on 2022-12-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoivakoti_browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osoite', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'asujat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Palvelukori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asukas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoivakoti_browser.asukkaat')),
                ('plv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoivakoti_browser.palvelut')),
            ],
        ),

    ]
