# Generated by Django 4.1.3 on 2022-12-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoivakoti_browser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopimus',
            name='osoite_id',
        ),
    ]
