# Generated by Django 4.1.3 on 2022-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoivakoti_browser', '0002_osoite_palvelukori_delete_asujat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tilaaja',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tilaaja',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Asujat',
        ),
        migrations.DeleteModel(
            name='Tilaajat',
        ),
        migrations.AlterModelOptions(
            name='palvelukori',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='osoite',
            table='osoite',
        ),
    ]
